# Generated by Django 4.2.5 on 2023-10-04 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('Standard', 'Standard'), ('Premium', 'Premium'), ('Luxury', 'Luxury')], max_length=20)),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
                ('min_ride_time', models.IntegerField(default=0)),
                ('max_ride_time', models.IntegerField(default=0)),
                ('min_waiting_time', models.IntegerField(default=0)),
                ('max_waiting_time', models.IntegerField(default=0)),
                ('min_km_driven', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_km_driven', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_per_minute', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('waiting_time_fee', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
