# Generated by Django 4.2.5 on 2023-10-05 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_pricingconfig_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricingconfig',
            old_name='min_km_driven',
            new_name='DBP',
        ),
        migrations.RemoveField(
            model_name='pricingconfig',
            name='max_ride_time',
        ),
        migrations.RemoveField(
            model_name='pricingconfig',
            name='max_waiting_time',
        ),
        migrations.RemoveField(
            model_name='pricingconfig',
            name='min_ride_time',
        ),
        migrations.RemoveField(
            model_name='pricingconfig',
            name='min_waiting_time',
        ),
    ]
